### ISSUE TITLE
Cannot get rowdy to return refresh token

### ISSUE THREAD

**Issue by neverfox** [lawliet89/rowdy#64]
If I run the docker example, and submit a request with offline_token=true, it doesn't return a refresh token in the response. Same thing if I configure the csv fixture for refresh tokens.

**Comment by neverfox** [comment]
```
PROTECTED_RESOURCE="https://www.example.com/protected/resource/"

REALM=http://localhost:8000
SERVICE=https://www.example.com
SCOPE=all

# Build the URL to query the auth server
AUTH_URL="${REALM}?service=${SERVICE}&scope=${SCOPE}&offline_token=true"

# Query the auth server to get a token -- replace the username and password
# below with the value from 1password
TOKEN=$(curl -s --user "mozart:password" "${AUTH_URL}")

# Get the access token from the JSON string: {"token": "...."}
ACCESS_TOKEN=$(echo ${TOKEN} | jq .token | tr -d '"')

# Get the refresh token
REFRESH_TOKEN=$(echo "${TOKEN}" | jq .refresh_token | tr -d '"')

# refresh token is null because it's not in the response
echo $REFRESH_TOKEN
```
docker-compose.override.yml
```
version: "2.1"
services:
  rowdy:
    environment:
      ROCKET_ENV: production
    ports:
      - "8000:80"
    volumes:
      - ./cli/test/fixtures:/app/test/fixtures
    command: [./rowdy-cli, noop, test/fixtures/config_noop.json]
```
